services:
  Anboo\ApiBundle\Controller\DocumentationController:
    arguments:
      - '@nelmio_api_doc.generator.default'
    tags: ['controller.service_arguments']

  Anboo\ApiBundle\Validator\EntityExistsValidator:
    arguments:
      - '@doctrine.orm.default_entity_manager'
    tags: ['validator.constraint_validator']

  Anboo\ApiBundle\Serializer\Normalizer\EntityNormalizer:
    public: false
    autowire: true
    autoconfigure: true
    tags: ['serializer.normalizer']

  Anboo\ApiBundle\Serializer\Normalizer\UuidNormalizer:
    public: false
    autowire: true
    autoconfigure: true
    tags:
      - { name: serializer.normalizer, priority: 255 }

  Anboo\ApiBundle\Serializer\Normalizer\IgnoredAttributesNormalizer:
    public: false
    autowire: true
    autoconfigure: true
    tags:
      - { name: serializer.normalizer, priority: 255 }
